# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SdTbPBSvW4DI-k-yT3cJ3tAZhzmI-MqS
"""

A=[[0,0,0,0,0,0,0,1,0,1,0,1,0],
   [0,0,0,0,0,0,0,0,1,0,1,0,0],
   [0,0,0,1,0,0,0,0,0,0,0,0,1],
   [0,0,1,0,1,0,0,1,0,0,0,0,0],
   [0,0,0,1,0,0,0,0,0,0,0,0,0],
   [0,0,0,0,0,0,0,1,0,0,0,0,0],
   [0,0,0,0,0,1,0,1,0,0,0,0,0],
   [1,0,0,1,0,0,1,0,0,0,0,1,0],
   [0,1,0,0,0,0,0,0,0,1,0,0,1],
   [1,0,0,0,0,0,0,0,1,0,1,0,0],
   [0,1,0,0,0,0,0,0,0,1,0,0,0],
   [1,0,0,0,0,0,0,1,0,0,0,0,0],
   [0,0,1,0,0,0,0,0,1,0,0,0,0]
   ]

def BFS(A,root):
  visited = [False] * len(A)
  queue=[root]
  visited[root]=True

  while queue:
    current_node = queue.pop(0)
    print(current_node, end='')

    for neighbor in range(len(A)):
      if A[current_node][neighbor] == 1 and not visited[neighbor]:
        queue.append(neighbor)
        visited[neighbor] = True

BFS(A,4)